FROM alpine:edge

RUN apk add --no-cache ca-certificates

RUN wget -q https://github.com/containernetworking/plugins/releases/download/v0.7.1/cni-plugins-amd64-v0.7.1.tgz -O /cni-plugins.tgz

COPY bin/tke-bridge-agent /
COPY scripts/install-agent.sh /

ENTRYPOINT ["/install-agent.sh"]