FROM ccr.ccs.tencentyun.com/tkeimages/tke-eni-agent:v3.2.0-alpha.0 AS CNI

FROM alpine:3.6

COPY --from=CNI /tke-route-eni /

RUN apk add --no-cache ca-certificates

COPY bin/tke-bridge-agent /

COPY scripts/install-cni.sh /

ENTRYPOINT ["/install-cni.sh"]